apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  AUTH: "UkVQTEFDRV9XSVRIX01PTkdPREJfQVVUSF9DT05ORUNUSU9OX1NUUklORw=="
  RABBITMQ_URL: "UkVQTEFDRV9XSVRIX1JBQkJJVE1RX0NPTk5FQ1RJT05fU1RSSU5H"
  REDIS_URL: "UkVQTEFDRV9XSVRIX1JFRElTX0NPTk5FQ1RJT05fU1RSSU5H"
---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
data:
  GOOGLE_CLIENT_ID: "UkVQTEFDRV9XSVRIX0dPT0dMRV9PQVVUSF9DTElFTlRfSUQ="
  GOOGLE_CLIENT_SECRET: "UkVQTEFDRV9XSVRIX0dPT0dMRV9PQVVUSF9DTElFTlRfU0VDUkVU"
  EMAIL_USER: "UkVQTEFDRV9XSVRIX0dPT0dMRV9FTUFJTF9BRERSRVNT"
  CLIENT_ID: "UkVQTEFDRV9XSVRIX0dPT0dMRV9PQVVUSF9DTElFTlRfSUQ="
  CLIENT_SECRET: "UkVQTEFDRV9XSVRIX0dPT0dMRV9PQVVUSF9DTElFTlRfU0VDUkVU"
  REFRESH_TOKEN: "UkVQTEFDRV9XSVRIX0dPT0dMRV9PQVVUSF9SRUZSRVNIX1RPS0VO"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
data:
  JWT_SECRET: "UkVQTEFDRV9XSVRIX0FfTE9OR19SQU5ET01fSldUX1NFQ1JFVA=="
---
apiVersion: v1
kind: Secret
metadata:
  name: aisecret
type: Opaque
data:
  GOOGLE_API_KEY: "UkVQTEFDRV9XSVRIX0dPT0dMRV9BUElfS0VZ"
